
INSERT INTO tbl_datagame
           (Id
		   ,Window
           ,PrivateMessages
           ,GlobalMessages
           ,GroupMessages
           ,Destroyed
           ,Killed
           ,Score
           ,TeamScore
           ,CapturedFlag
           ,GoalFlag
           ,ViewMaps
           ,ViewAvatar
           ,ViewAvatarFocus
           ,ViewEnemyAvatar
           ,ViewEnemyAvatarFocus
           ,ViewScoreTable
           ,Game
           ,ClientNumber
           ,Username
           ,Extension
           ,Date
           ,Time
           ,Team
           ,GameMode
           ,Ammunition
           ,Life
           ,Weapon
           ,Host
           ,AutoDestroyed
           ,ChangeWeapon
           ,StoleFlag
           ,PickedUpFlag
           ,LostFlag
           ,DroppedFlag
           ,ReturnedFlag
           ,HuntedFlag
           ,ScoredWithFlag
           ,ScoredCarryingFlag
           ,RecieveMessages
           ,Armour
           ,Shots
           ,EffectiveShot
           ,EffectiveShotEnemy
           ,EffectiveShotTeammate
           ,EffectiveShotToStandardBearer
           ,KillStandardToBearer
           ,StandardBearerKillEnemys
           ,StandarBearerEffectiveShot)
     VALUES
           (NULL
           ,10
           ,15
           ,10
           ,20
           ,13
           ,20
           ,22
           ,3
           ,0
           ,12
           ,33
           ,44
           ,41
           ,10
           ,4
           ,1
           ,12
           ,'servkey'
           ,'extension'
           ,'01/10/12'
           ,'10:00'
           ,1
           ,2
           ,10
           ,10
           ,9
           ,'127.0.0.1'
           ,23
           ,11
           ,2
           ,2
           ,33
           ,12
           ,92
           ,1
           ,5
           ,8
           ,86
           ,4
           ,66
           ,76
           ,12
           ,32
		   ,10
           ,21
           ,10
           ,11,
		   10);



INSERT INTO tbl_datagame  VALUES (NULL,10,15,10,20,13,20,22,3,0,12,33,44,41,10,4,1,12,'servkey','extension','01/10/12','10:00',1,2,10,10,9,'127.0.0.1',23,11,2,2,33,12,92,1,5,8,86,4,66,76,12,32,10,21,10,11,10, 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15);